[#ftl/]
[@b.select name="apply.batch.id" items=batches label="毕业年月"/]
[@b.textfield name="apply.std.code" label="学号"/]
[@b.textfield name="apply.std.name" label="姓名"/]
[@b.textfield name="apply.std.state.grade" label="年级"/]
[@b.select name="apply.std.state.department.id" items=departs label="所在学院" empty="..."/]
[@b.textfield name="apply.std.state.major.name" label="专业"/]
[@b.textfield name="apply.std.state.squad.name" label="班级"/]
